weather/urls.py
from django.conf.urls import url

from .views import HomeView, CityListView, DeleteCityView

app_name = 'weather'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^cities$', CityListView.as_view(), name='search_results'),
    url(r'^delete-city$', DeleteCityView.as_view(), name='delete_city'),
    #url(r'^(?P<city_name>\\d+)$', CityWeatherView.as_view(), name='city_weather')
]

weather_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather/models.py
from django.db import models
from django.urls import reverse


class City(models.Model):
    name = models.CharField(max_length=25)
    temperature = models.DecimalField(decimal_places=2, max_digits=4, default=None, null=True)
    description = models.CharField(max_length=60, default='', null=True)
    icon = models.CharField(max_length=25, default='', null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    def __str__(self):
        return self.name


    class Meta:
        verbose_name_plural = 'cities'

weather/forms.py
from django.forms import ModelForm, Select
from .models import City


class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name': Select(attrs={
            'class': 'input',
            'id': 'city',
            'required': True,
            'placeholder': 'Search',
        })}

weather/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView
from django.views.generic.base import TemplateView
from .models import City
from .forms import CityForm
from .service import weather_by_city_name
from django.http import JsonResponse
from datetime import datetime
from django.utils.dateparse import parse_date
from dateutil import parser

from django.core.paginator import Paginator

import requests


class HomeView(TemplateView):
    template_name = 'home.html'
    partial_template_name = 'city_weather_partial.html'

    def get_city_data(self, request):
        form = CityForm(request.POST)
        if not form.is_valid():
            raise Exception('Invalid city name')
        city_name = form.cleaned_data['name']
        city_data = weather_by_city_name(city_name)
        if not city_data:
            raise Exception('City weather not found')
        exists = City.objects.filter(name=city_name).first()
        if not exists:
            city = form.save(commit=False)
            city.description = city_data['description']
            city.icon = city_data['icon']
            city.temperature = city_data['temperature']
            city.save()
        return city_data

    def get(self, request, *args, **kwargs):
        return super(HomeView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['form'] = CityForm()

        return context

    def post(self, request, *args, **kwargs):
        error = False
        city_data = None
        try:
            city_data = self.get_city_data(request)
        except Exception as e:
            error = str(e)

        return render(request, self.partial_template_name, {
            'error': error,
            'city_data': city_data
        })


class CityListView(ListView):
    template_name = 'cities.html'
    model = City
    paginate_by = 3

    def get_queryset(self):
        query = 'SELECT * FROM weather_city'
        date_from = self.request.GET.get('date_from')
        date_to = self.request.GET.get('date_to')
        params = []
        if date_from:
            date_from = parser.parse(date_from).strftime('%Y-%m-%d')
            params.append(date_from)
            query += " WHERE created >= %s "
        if date_to:
            date_to = parser.parse(date_to).strftime('%Y-%m-%d')
            params.append(date_to)
            if date_from:
                query += ' AND '
            else:
                query += ' WHERE '
            query += " created <= %s "
        query += ' ORDER BY created DESC'

        return list(City.objects.raw(query, params))

    def get_context_data(self, **kwargs):
        context = super(CityListView, self).get_context_data(**kwargs)
        date_from = self.request.GET.get('date_from', '')
        date_to = self.request.GET.get('date_to', '')

        filter = []

        if date_from:
            filter.append('date_from=' + date_from)

        if date_to:
            filter.append('date_to=' + date_to)

        filter = '&'.join(filter)

        if filter:
            filter = '&' + filter

        context['filter'] = filter
        context['date_from'] = date_from
        context['date_to'] = date_to

        return context


class DeleteCityView(TemplateView):
    def post(self, request, *args, **kwargs):
        id = request.POST.get('id')
        City.objects.get(id=id).delete()
        return JsonResponse(
            {'success': True}
        )

weather/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf_token" content="{{csrf_token}}" id="csrf_token">
    <title>Weather - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/css/datepicker.min.css"/>
    <link rel="shortcut icon" href="{% static 'img/sun.png' %}" type="image/x-icon">
</head>

<body>
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Mini weather portal
                <nav class="my-2 my-md-0 mr-md-3">
                    <a class="p-2 text-dark" href="/">Wether</a>
                    <a class="p-2 text-dark" href="cities">Existing</a>
                </nav>
            </h1>
        </div>
    </div>
</section>

{% block content %}{% endblock %}

<footer class="footer">
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/air-datepicker/2.2.3/js/datepicker.min.js"></script>
<script src="{% static 'js/app.js' %}"></script>
</body>

</html>

weather/templates/cities.html
{% extends 'base.html' %}

{% block title %}Cities list{% endblock %}

{% block content %}
<section class="section">
    <div class="container ">
        <div class="columns ">
            <form action="" method="GET" class="field has-addons">
                <div class="control">
                    <input class="input" autocomplete="off" value="{{ date_from }}" type="text" name="date_from"
                           id="date_from" placeholder="Date from">
                </div>
                <div class="control">
                    <input class="input" autocomplete="off" value="{{ date_to }}" type="text" name="date_to"
                           id="date_to" placeholder="Date to">
                </div>
                <div class="control">
                    <button class="button is-info" type="submit">
                        Search
                    </button>
                </div>
            </form>
            <div class="column is-offset-4 is-4" id="cities-list">
                {% for city in object_list %}
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-50x50">
                                <img src="http://openweathermap.org/img/w/{{ city.icon }}.png" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <span class="title">{{ city.name }}</span>
                                    <br>
                                    <span class="subtitle">{{ city.temperature }} °C</span>
                                    <br> {{ city.description }}
                                </p>
                            </div>
                        </div>
                        <div class="media-right">
                            <a href="#" class="js-delete-city" data-id="{{ city.id }}">
                                <button class="delete"></button>
                            </a>
                        </div>
                    </article>
                </div>
                {% empty %}
                <li>No cities found.</li>
                {% endfor %}
            </div>
            {% if is_paginated %}
            <nav aria-label="Page navigation conatiner"></nav>
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}{{ filter }}" class="page-link">&laquo; PREV </a>
                </li>
                {% endif %}
                {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}{{ filter }}" class="page-link"> NEXT &raquo;</a></li>
                {% endif %}
            </ul>
            </nav>
        </div>
        {% endif %}
    </div>
    </div>
</section>
{% endblock %}

weather/templates/city_weather.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ city_weather.city_name }}{% endblock %}

{% block styles %}<link rel="stylesheet" href="{% static 'css/city_weather.css' %}" />{% endblock %}

{% block content %}
    <div id="weather">
        {% if city_weather.error %}
            <h2>Cannot get weather (HTTP Error)</h2>
        {% else %}
            {% include 'city_weather_partial.html' %}
        {% endif %}
    </div>

    {% if not city_weather.error %}
        <p id="refresh-in">Refresh in:</p>
        <div class="progress">
            <div id="progress-bar" class="progress-bar progress-bar-striped active" style="width:100%"></div>
        </div>

        <input type="hidden" id="url_variable" value="{% url 'weather:city_weather' city_name  %}">
    {% endif %}
{% endblock %}

{% if not city_weather.error %}
    {% block scripts %}
        <script src="{% static 'js/city_weather.html.js' %}"></script>
    {% endblock %}
{% endif %}

weather/templates/city_weather_partial.html
{% if error %}
<div class="notification is-danger">
    {{ error }}
    <button class="del-msg delete"
            onclick="document.getElementsByClassName('notification')[0].style.display='none'"></button>
</div>
{% else %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-offset-4 is-4">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-50x50">
                                <img src="http://openweathermap.org/img/w/{{ city_data.icon }}.png" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <span class="title">{{ city_data.city }}</span>
                                    <br>
                                    <span class="subtitle">{{ city_data.temperature }} °C</span>
                                    <br> {{ city_data.description }}
                                </p>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </div>
</section>
{% endif %}

weather/templates/home.html
{% extends 'base.html' %}

{% block title %}Search city{% endblock %}

{% block content %}
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-offset-4 is-4">
                <form method="POST" id="city-form">
                    {% csrf_token %}
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            {{ form.name }}
                        </div>
                        <div class="control">
                            <button type="submit" class="button is-info">
                                Add City
                            </button>
                        </div>
                    </div>
                    <div id="city-weather"></div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

weather/templates/searchform.html
<form id="searchform" action="{% url 'weather:search_results' %}" method="get">
    <div class="input-group">
        <input id="searchbox" class="form-control" name="q" type="text"
               placeholder="Search cities" value="{{ q|default:'' }}" required>
        <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
            </button>
        </div>
    </div>
</form>